# Generated by Django 4.2.9 on 2024-02-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Board Name')),
                ('color', models.CharField(max_length=20, verbose_name='Board Color')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Reminder')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True)),
                ('assignee', models.ManyToManyField(blank=True, to='reminders.myuser')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminders.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='people',
            field=models.ManyToManyField(to='reminders.myuser'),
        ),
    ]
