# Generated by Django 4.2.9 on 2024-02-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
