# Generated by Django 4.2.9 on 2024-02-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
